version: '2'
services:
  mysql-db:
        image: mysql
        container_name: mysql-db
        ports:
          - 3306:3306
        environment:
          - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}

  app:
    image: flask-todo-app
    container_name: flask-todo
    ports:
      - 5000:5000
    environment:
          - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            MYSQL_HOST=${MYSQL_HOST}
            MYSQL_USER=${MYSQL_USER}
            MYSQL_DB=${MYSQL_DB}
    depends_on:
      - mysql-db