version: '2'
services:
  mysql-db:
        image: mysql
        container_name: mysql-db
        ports:
          - 3306:3306
        environment:
          - MYSQL_ROOT_PASSWORD=ahmed1998

  app:
    image: flask-todo-app
    container_name: flask-todo
    ports:
      - 5000:5000
    depends_on:
      - mysql-db